# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'StickyTableView' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SnapKit', '~> 5.0.0'

  # Pods for StickyTableView

  target 'StickyTableViewTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'StickyTableViewUITests' do
    # Pods for testing
  end

end
